name: Deploy to Pages Repo

on:
  push:
    branches: [ "docs" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Target Repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          external_repository: lyqgzbl/wuwa_pages
          publish_branch: main
          publish_dir: ./docs
          destination_dir: task
          keep_files: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: "deploy: sync quest_tracker from upstream"
